---
version: "3.8"
services:
  redis:
    image: "redis/redis-stack:latest"
    container_name: "redis-stack"
    ports:
    - "${REDIS_PORT:-6379}:6379"
    - "${REDIS_INSIGHT_PORT:-8001}:8001"
    environment:
    - "REDIS_ARGS=--requirepass \"\""
    volumes:
    - "redis_data:/data"
    restart: "unless-stopped"
    healthcheck:
      test:
      - "CMD"
      - "redis-cli"
      - "ping"
      interval: "30s"
      timeout: "10s"
      retries: 3
  app:
    build:
      context: ".."
      dockerfile: "docker/Dockerfile"
    container_name: "llm-cache-app"
    ports:
    - "${APP_PORT:-8080}:8080"
    environment:
    - "SPRING_PROFILES_ACTIVE=ollama"
    - "REDIS_HOST=redis"
    - "REDIS_PORT=6379"
    - "LLMPROVIDER_ACTIVE=ollama"
    - "LLMPROVIDER_OLLAMA_BASE_URL=${LLMPROVIDER_OLLAMA_BASE_URL:-http://host.docker.internal:11434}"
    - "LLMPROVIDER_OLLAMA_MODEL=${LLMPROVIDER_OLLAMA_MODEL:-qwen2.5-coder:3b}"
    - "LLMPROVIDER_OLLAMA_ENABLED=true"
    - "LLMPROVIDER_OPENAI_ENABLED=false"
    depends_on:
      redis:
        condition: "service_healthy"
    restart: "unless-stopped"
volumes:
  redis_data: null
